

alter session set nls_date_format = 'MM-DD-YYYY HH24:MI:SS';

CREATE TABLE FLTRESV(
  FLIGHT_NUM NUMBER PRIMARY KEY, 
  DEPARTURE_TIME TIMESTAMP, 
  DURATION NUMBER, 
  CAPACITY NUMBER, 
  SEASONAL NUMBER(1), 
  ORIGIN VARCHAR2(50 BYTE), 
  DESTINATION VARCHAR2(50 BYTE), 
  REQUEST XMLTYPE
);

COMMIT;
